### ISSUE TITLE
Error while running npm start

### ISSUE THREAD

**Issue by ieiayaobb** [yiminghe/learning-react#5]
Could you help to check the error messages?
npm start

> learning-react@1.0.0 start /Volumes/Content/studyworkspace/learning-react
> node --harmony server

/Volumes/Content/studyworkspace/learning-react/node_modules/babel-core/lib/babel/transformation/file/index.js:604
      throw err;
            ^
TypeError: /Volumes/Content/studyworkspace/learning-react/example/code-share/server.jsx: Cannot read property 'declareTemporary' of null
    at getOuterFnExpr (/Volumes/Content/studyworkspace/learning-react/node_modules/babel-core/node_modules/regenerator/lib/visit.js:287:35)
    at Context.types.PathVisitor.fromMethodsObject.visitFunction (/Volumes/Content/studyworkspace/learning-react/node_modules/babel-core/node_modules/regenerator/lib/visit.js:107:23)
    at Context.invokeVisitorMethod (/Volumes/Content/studyworkspace/learning-react/node_modules/babel-core/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:306:43)
    at Visitor.PVp.visitWithoutReset (/Volumes/Content/studyworkspace/learning-react/node_modules/babel-core/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:180:28)
    at visitChildren (/Volumes/Content/studyworkspace/learning-react/node_modules/babel-core/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:226:21)
    at Visitor.PVp.visitWithoutReset (/Volumes/Content/studyworkspace/learning-react/node_modules/babel-core/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:188:16)
    at Visitor.PVp.visit (/Volumes/Content/studyworkspace/learning-react/node_modules/babel-core/node_modules/regenerator/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:124:25)
    at Function.transform (/Volumes/Content/studyworkspace/learning-react/node_modules/babel-core/node_modules/regenerator/lib/visit.js:30:11)
    at TraversalPath.Func (/Volumes/Content/studyworkspace/learning-react/node_modules/babel-core/lib/babel/transformation/transformers/other/regenerator.js:35:30)
    at TraversalPath.call (/Volumes/Content/studyworkspace/learning-react/node_modules/babel-core/lib/babel/traversal/path/index.js:928:28)

**Comment by yiminghe** [comment]
try rm node_modules and re npm install

**Comment by ieiayaobb** [comment]
I tried several times but the problem still exists, I'm going to paste the log content from npm-debug.log file.

 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'start' ]
2 info using npm@2.7.5
3 info using node@v0.12.2
4 verbose node symlink /usr/local/bin/node
5 verbose run-script [ 'prestart', 'start', 'poststart' ]
6 info prestart learning-react@1.0.0
7 info start learning-react@1.0.0
8 verbose unsafe-perm in lifecycle true
9 info learning-react@1.0.0 Failed to exec start script
10 verbose stack Error: learning-react@1.0.0 start: `node --harmony server`
10 verbose stack Exit status 1
10 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
10 verbose stack     at EventEmitter.emit (events.js:110:17)
10 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:14:12)
10 verbose stack     at ChildProcess.emit (events.js:110:17)
10 verbose stack     at maybeClose (child_process.js:1015:16)
10 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
11 verbose pkgid learning-react@1.0.0
12 verbose cwd /Volumes/Content/studyworkspace/learning-react
13 error Darwin 14.4.0
14 error argv "node" "/usr/local/bin/npm" "start"
15 error node v0.12.2
16 error npm  v2.7.5
17 error code ELIFECYCLE
18 error learning-react@1.0.0 start: `node --harmony server`
18 error Exit status 1
19 error Failed at the learning-react@1.0.0 start script 'node --harmony server'.
19 error This is most likely a problem with the learning-react package,
19 error not with npm itself.
19 error Tell the author that this fails on your system:
19 error     node --harmony server
19 error You can get their info via:
19 error     npm owner ls learning-react
19 error There is likely additional logging output above.
20 verbose exit [ 1, true ]

**Comment by yiminghe** [comment]
try pull and re npm start

**Comment by ieiayaobb** [comment]
problem solved, thanks a lot
